git config --global user.email 1114891937@qq.com
git config --global user.name WeiXia
git checkout main
git reset --hard origin/main
git pull
conda activate django
python manage.py migrate
python /home/xw/backend/manage.py runserver 0.0.0.0:8000
(base) xw@VM-20-3-ubuntu:~/backend$ git config --global user.email 1114891937@qq
.com
(base) xw@VM-20-3-ubuntu:~/backend$ git config --global user.name WeiXia
(base) xw@VM-20-3-ubuntu:~/backend$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
(base) xw@VM-20-3-ubuntu:~/backend$ git reset --hard origin/main
HEAD is now at 40e1c66 完成简单测试
(base) xw@VM-20-3-ubuntu:~/backend$ git pull
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 378 bytes | 378.00 KiB/s, done.
From https://github.com/summer-semester-backend/backend
   40e1c66..7e8a091  main       -> origin/main
Updating 40e1c66..7e8a091
Fast-forward
 team/tools.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
(base) xw@VM-20-3-ubuntu:~/backend$ conda activate django
(django) xw@VM-20-3-ubuntu:~/backend$ python manage.py migrate
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'user' isn't unique. You may not be able to reverse
 all URLs in this namespace
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, team, user
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
  Applying user.0001_initial... OK
  Applying team.0001_initial... OK
  Applying team.0002_auto_20220802_1631... OK
  Applying team.0003_invitation... OK
(django) xw@VM-20-3-ubuntu:~/backend$ python /home/xw/backend/manage.py runserve
r 0.0.0.0:8000
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'user' isn't unique. You may not be able to reverse
 all URLs in this namespace

System check identified 1 issue (0 silenced).
August 03, 2022 - 10:20:20
Django version 4.0.4, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

